version: '3'
services:
  fluentd:
    container_name: fluentd
    build: ./fluentd
    links:
      - "elasticsearch"
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    links:
      - "elasticsearch"
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
